# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.cache/wt [current_project]
set_property parent.project_path F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/DVP_Capture/DVP_Capture.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/camera_init/camera_init.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/new/crc32_d8.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ddr3_ctrl_2port/ddr3_ctrl_2port.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/disp_driver/disp_driver.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/new/eth_tx_ctrl.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/new/eth_udp.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ddr3_ctrl_2port/fifo2mig_axi.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/camera_init/i2c_control/i2c_bit_shift.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/camera_init/i2c_control/i2c_control.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/image_stitche/image_stitche_x.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/new/ip_checksum.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/camera_init/ov5640_init_table_rgb.v
  F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/top/ov5640x2_ddr3_tft.v
}
read_ip -quiet F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/pll/pll.xci
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/pll/pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/pll/pll.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/pll/pll_ooc.xdc]

read_ip -quiet F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xci
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo_ooc.xdc]

read_ip -quiet F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/wr_ddr3_fifo/wr_ddr3_fifo.xci
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/wr_ddr3_fifo/wr_ddr3_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/wr_ddr3_fifo/wr_ddr3_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/wr_ddr3_fifo/wr_ddr3_fifo_ooc.xdc]

read_ip -quiet F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/image_buffer/image_buffer.xci
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/image_buffer/image_buffer.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/image_buffer/image_buffer_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/image_buffer/image_buffer_ooc.xdc]

read_ip -quiet f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo.xci
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/constrs_1/new/io.xdc
set_property used_in_implementation false [get_files F:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/constrs_1/new/io.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ov5640x2_ddr3_tft -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ov5640x2_ddr3_tft.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ov5640x2_ddr3_tft_utilization_synth.rpt -pb ov5640x2_ddr3_tft_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
