# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo.xci
# IP: The module: 'eth_tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_tx_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo.xci
# IP: The module: 'eth_tx_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/ov5640x2_ddr3_tft_test/ov5640x2_ddr3_tft.srcs/sources_1/ip/eth_tx_fifo/eth_tx_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_tx_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
