# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xci
# IP: The module: 'rd_ddr3_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_ddr3_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_ddr3_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_ddr3_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xci
# IP: The module: 'rd_ddr3_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_ddr3_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_ddr3_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/Xilink_FPGA/Project/ov5640x2_ddr3_tft/ov5640x2_ddr3_tft.srcs/sources_1/ip/rd_ddr3_fifo/rd_ddr3_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rd_ddr3_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
